### ISSUE TITLE
Computer turns off when using two GPU

### ISSUE THREAD

**Issue by Edouard2laire** [fangq/mcx#228] opened 2024-07-23 22:32 UTC
Hello, 

I am coming to report a peculiar bug.  We have a computer with 2 GPU (GTX 1080 Ti ). 
if i use each of them separately for MCXlab, it is working well but if I try to start a simulation using both GPUs, then the computer will turn off after a few seconds. 

Do you have any idea of what could be causing the issue? 

Both GPUs are powered using a G 750M power (ccooler master): https://www.coolermaster.com/en-global/products/g750m/. Fron the case, it should be able to power 750W which should be enough, i think?

![image](https://github.com/user-attachments/assets/09d0a501-826b-4f93-b82a-e113d5bb5858)

Thanks a lot
Edouard

**Comment by kalvdans** [comment] 2024-07-23 23:05
It sounds indeed like the power consumption. Each GPU draws 250W according to https://en.m.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units and the power supply also have to power the cpu, hard disk, fans.

**Comment by Edouard2laire** [comment] 2024-07-24 00:43
> It sounds indeed like the power consumption. Each GPU draws 250W according to https://en.m.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units and the power supply also have to power the cpu, hard disk, fans.


The two GPUs would then use 500W leaving 250W for the cpu, fans ... shoudn't it be enough ? If that is the issue, how much power would you recommend?


> Try trottling down the GPU:s using `sudo nvidia-smi -pl 200`

Thx. i'll try and let you know if that works.

Edouard

**Comment by fangq** [comment] 2024-07-24 15:44
@Edouard2laire, I too suspect it is related to power issue, not a bug in mcx, but I also acknowledge that I have a few boxes using 750W to drive comparable GPUs with no issue.

I suspect that the issue might be caused by degenerated performance from either the power supply or your GPUs - cleaning dust and ensuring sufficient air flow and fan speed could be one way to verify. You should use [`nvtop`](https://www.cyberciti.biz/hardware/nvtop-command-in-linux-to-monitor-nvidia-amd-intel-gpus/) to see the power draw and temperature of your GPU when running simulations on individual GPU and see if you can capture any abnormality; you could also use `sensors` command to see GPU/chassis fan speed and temperature. if system has a crash, you can look at the system logs under `/var/log`.

**Comment by fangq** [comment] 2024-08-18 16:20
I am closing this ticket. if something related to mcx is identified, please feel free to reopen.

**Closed by fangq** 2024-08-18 16:20 UTC

**Comment by Edouard2laire** [comment] 2025-03-05 19:23
Hi, 
I confirm that changing the power supply fixed the issue. Thx :)
